spring:
  datasource:
    url: jdbc:mysql://103.160.2.183:3306/gear3s_db
    username: root
    password: 123456a@
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  redis:
    host: 103.160.2.183
    port: 6377
  rabbitmq:
    host: 103.160.2.183
    port: 5671
    username: gear
    password: 3s

rabbitmq:
  queue: gear3s_queue
  exchange: gear3s_exchange
  routingKey: gear3s_routing_key