server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://103.160.2.183:3306/gear3s_db
    username: root
    password: 123456a@
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    #static-path-pattern: /static/**

jwt:
  privateKey: mB4Mn+ISn7uhxTHyewNaaCi+ZxDw8Hxci6JaTLR4gcU=
