spring:
  datasource:
    url: jdbc:mysql://103.160.2.183:3306/gear3s_db
    username: root
    password: 123456a@
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none