server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://103.160.2.183:3306/gear3s_db
    username: root
    password: 123456a@
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
  redis:
    host: 103.160.2.183
    port: 6377

#    static-path-pattern: /resources/**, /css/**, /js/**, /vendor/**

jwt:
  privateKey: mB4Mn+ISn7uhxTHyewNaaCi+ZxDw8Hxci6JaTLR4gcU=

logging:
  level:
    root: info
  file:
    name: ../../logs/gear3s-log.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %magenta([%thread]) %clr(${LOG_LEVEL_PATTERN:-%5p}) %cyan(%logger{37}.%M) - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{37}.%M - %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: ../../logs/archived/gear3s-log.%d{yyyy-MM-dd}.%i.log
      max-file-size: 50MB

uploads:
  path: ../../uploads/images
  defaultAvatar: person-icon.png








